### ISSUE TITLE
retry backgroundImage in tag style

### ISSUE THREAD

**Issue by HughDai** [Nikaple/assets-retry#80]
我的应用代码是这样的
```javascript
window.assetsRetryStatistics = window.assetsRetry({
    domain: ['cdn.a.com', 'cdn.b.com'],
    maxRetryCount: 1
})
```
css中的background-image会自动添加备用域名cdn.b.com域名的url
```css
.normal-module_contentLessonsPracticeNothing_2H-mB::before {
    background-image: url(http://cdn.a.com/img/no-task.7e4726d6.png), 
        url(http://cdn.b.com/img/no-task.7e4726d6.png) !important;
}
```
这样浏览器会向这两个资源都发起请求，请问这样是否符合css背景图片重试的预期。
谢谢！
